ReBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('begin.urls',namespace='begin')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('main/',include('main.urls',namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import LoginView,ProfileView,SignupView,LogoutView

app_name='accounts'
urlpatterns=[
    path('login/',LoginView,name='login'),
    path('profile/',ProfileView,name='profile'),
    path('signup/',SignupView,name='signup'),
    path('logout/',LogoutView,name='logout'),


]

begin/urls.py
from django.urls import path
from .views import mainpage,home,aboutus,service,contact
app_name='begin'

urlpatterns=[
    path('',mainpage,name='index'),
    path('home/',mainpage,name='home'),
    path('about-us/',aboutus,name='about-us'),
    path('service/',service,name='service'),
    path('contact/',contact,name='contact')

]

main/urls.py
from django.urls import path
from .views import BuyBooks,SellBooks,BuyDetailView,BuyListView,SellCreateView,SellUpdateView,SellDeleteView,searchbooks
from . import views
app_name='main'
urlpatterns=[
    path('buy/',BuyListView.as_view(),name='buy'),
    path('sell/',SellCreateView.as_view(),name='sell'),
    path('detail/<int:pk>/',BuyDetailView.as_view(),name='detail'),
    path('detail/<int:pk>/update/',SellUpdateView.as_view(),name='update'),
    path('detail/<int:pk>/delete/',SellDeleteView.as_view(),name='delete'),
    path('search/',searchbooks,name='search'),
    path('wishlist/add/<int:book_id>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('wishlist/', views.view_wishlist, name='view-wishlist'),
    path('mybooks/', views.view_myBooks, name='view-my-books'),
    path('mark-as-sold/<int:book_id>/', views.mark_as_sold, name='mark_as_sold'),
    path('transaction-history/', views.transaction_history, name='transaction_history'),
    path('add-review/', views.add_review, name='add_review'),


]

begin/models.py
from django.db import models

class Contact(models.Model):
    sn=models.AutoField(primary_key=True)
    name=models.CharField(max_length=128)
    email=models.CharField(max_length=128)
    phone=models.CharField(max_length=20)
    content=models.TextField()


    def __str__(self):
        return self.name

begin/views.py
from django.shortcuts import render
from .models import Contact
from django.contrib import messages

# Create your views here.
def mainpage(request):
    return render(request,'begin/index.html')

def home(request):
    return render(request,'begin/base.html')

def aboutus(request):
    return render(request,'begin/about-us.html')

def service(request):
    return render(request,'begin/service.html')

def contact(request):
    if request.method=='POST':
        print(request.POST)
        name=request.POST['name']
        email=request.POST['email']
        phone=request.POST['phone']
        content=request.POST['content']
        print(name,email,phone,content)
        if len(name)<1 or len(email)<3 or len(phone)<5 or len(content)==0:
            messages.error(request,'Please fill the form correctly')
        else:
            contact=Contact(name=name,email=email,phone=phone,content=content)
            contact.save()
            messages.success(request,'Your message has been successfully sent')


    return render(request,'begin/contact.html')

begin/templates/begin/about-us.html
{% extends 'begin/base.html' %}

{% load static %}
{% block body %}

 <section id="about-us">
    <div class="container">
      <h1 class="title text-center">About ReBook Connect</h1> <br> <br> <br>  <br>
      <div class="row">
        
        
        <div class="col-md-6 about-us">
          <!--<p class="about-title">Why we're different?</p>-->
            <img src = "{% static 'images/logo1.png' %}" class="about-us-img"/> <br>
          
        </div>
        
      </div>
      <div class="row">
        <div class="col-md-12">
          <p>          ReBook Connect is a platform to buy and sell books easily. We connect buyers and sellers, making book exchanges simple and secure.
          </p>
          <ul>
            <li> <strong>Our Mission for Sustainability:</strong> At ReBook Connect, we are committed to fostering a sustainable marketplace where second-hand books are easily accessible. By encouraging book reuse, we help reduce waste, conserve valuable resources, and promote an eco-friendly lifestyle among our users.
            <li><strong>Seamless User Experience:</strong> Our platform is designed to ensure a smooth experience for buyers and sellers. Features like member login, intuitive account management, and streamlined book listing processes make it easy to find and share books within our community.
            </li>
            <li><strong>Building a Book-Loving Community: </strong>ReBook Connect creates meaningful connections by bringing readers, students, and sellers together in one place. By providing an affordable option for acquiring books, we support a community that values knowledge sharing and sustainable living.
            </li>
            <li> <strong>Empowering Sellers to Share Knowledge: </strong>Our system enables sellers to easily list, update, or remove books. This flexibility ensures users have access to accurate, current listings, helping sellers find new homes for their books while making reading affordable for all.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

begin/templates/begin/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'begin/style.css' %}">
    <title>ReBook Connect</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
		  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
          <link rel="shortcut icon" type="image/png" href="{% static 'images/logo1.png' %}"/>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
		integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	
    
    <style>
		@import url('https://fonts.googleapis.com/css2?family=Aclonica&display=swap');

        body {
    min-height: 100vh; /* Make the body take up the full viewport height */
    display: flex;
    flex-direction: column; /* Stack the content vertically */
    background-color: #E7E7E5;
}

.container {
    flex-grow: 1; /* Ensure the container grows to fill available space */
}
.one{
font-size:30px;
text-decoration:none;
margin:10px 5px 0 5px;
float:right;
top:5px;
color: white;

}
.one:hover{

	border: none;
	color: grey;
	text-decoration: underline;
}

.basenav{
background-color:#084787;
color:white;
font-weight: bold;
margin:0 0 0 0;
padding-bottom: 120px;
width: 100%;
}
.formreg{

margin:110px 10px 10px 10px;
padding:10px 10px;
height:130vh;
width:50vw;
left: 100px;

background-color:white;



}
.formlog{
margin:50px 10px 10px 40px;
padding:10px 10px;
height:90vh;
width:50vw;
left: 100px;

background-color:white;


}
.indeximg{
	background-color: rgb(142, 141, 141);
}

#services
{
    
    background-image: url('/static/images/E7E7E5.png');
    padding: 80px 0;
    height:100%;
    width:100%;
    background-size:cover;
    filter:blur(80%);
    font-weight: bolder;


}
.servicediv{
	margin-top: 10%;
	color: black;
	font-size: 30px;
    font-weight: bolder;
    
}
#about-us
{

    padding-bottom: 50px;
    padding-top: 45px;
    margin:80px 0 0 80px;
}

#about-us ul li{
    margin: 20px 0 0 0;
}
#about-us ul{
    margin-left: 20px;

}
.form-control{
	width: 100%;
	color: black;
}
.about-us-img{
float:center;
height:180px;}

#mainh1{
position:absolute;
top:50%;
font-size:60px;
font-weight: normal;
color: rgb(8, 200, 243);
text-align:center;
font-family: 'Aclonica', sans-serif;;

}
#pmain{
position:absolute;
top:50%;
font-size:40px;
font-weight: normal;
color: black;
left:25%;
}

<!--service-->
div p{
margin-top:50%;
}
.alert{
top:30%;
}
<!--profile-->
.content-section {
  background: #ffffff;
  padding: 10px 20px;
  border: 1px solid #dddddd;
  border-radius: 3px;
  margin-bottom: 20px;
}
.card{
border:2px solid black;
}


<!--main app-->
.container {
    display: flex;
flex-direction: row;
flex-wrap: wrap;
  }

	.containerone {
    display: flex;
flex-direction: row;
flex-wrap: wrap;
  }
   .card{
 border:1px solid black;
}
.card-me{

margin:90px 20px 20px 20px;
float:left;
}
.detail{
margin-top:250px;
width:70%;
}

.image-side{
float:right;
}
.form-inline{
margin-top:150px;

}
.sell-form{
margin:100px 15px 0 20px;
width:50%;
height:80%;
padding:100px 10px 10px 100px;
}

 label{
                    font-size: 18px;
                    font-weight: 600;
                }
                input{
                    margin-bottom: 0.5rem;
                    padding: 0px 6px;
                    width: 30%;
                    height: 32px;
                }

               .ubutton{
                  background: #12273c;
                  color: white;
                  font-weight: 600;
                  border-radius: 0.6em;
                  border: none;
                  padding: 10px 40px;
                  font-size: 20px;
                  margin-bottom: 20px;
                  margin-left: 8px;
                  text-decoration: none;
                  outline: none !important;
               }
			   .ubutton:hover{
				   color: white;
				   border: 1px solid white;
                   background-color: #084787;
			   }
               #updatebutton:hover{
                      font-size: 21px;

               }
               .media{
               align-items: center;
                   padding-top: 180px;
               }
               .account-img{
                      outline: #0060b1;
               }
               .media-body{
                      display: inline-block;
                      margin: 30px 0px 0px 28px;
               }
.active-item{
	color: black;

}
.normal-item{
	color: white;
}
/* General styling for the dropdown container */
.nav-item {
    position: relative;
    display: inline-block;
}

/* Hide the dropdown menu initially */
.dropdown-menu {
    display: none;
    position: absolute;
    background-color: white;
    min-width: 160px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    z-index: 1;
    padding: 12px;
    list-style-type: none;
    border-radius: 4px;
}

/* Styling for dropdown items */
.dropdown-menu a {
    color: black;
    padding: 8px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-menu a:hover {
    background-color: #f1f1f1;
}

/* Show the dropdown when hovering over the "My Account" link */
.nav-item:hover .dropdown-menu {
    display: block;
}


.table th {
        background-color: #08C8F3; /* Blue color */
        color: white;
    }


</style>
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
  <strong>Message:</strong> {{message}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}

{% if user.is_authenticated %}
<nav class="basenav">
<h1>ReBook Connect</h1> <br>
<ul>
	<li>


			<a class="one" href="{% url 'accounts:logout' %}">Logout</a>
			<a class="one" href="{% url 'begin:contact' %}"> Contact Us</a>

			<a class="one" href="{% url 'accounts:profile' %}">Profile</a>
		<a class="one" href="{% url 'main:buy' %}">Buy</a>
			<a class="one" href="{% url 'main:sell' %}">Sell</a>
			<a class="active one" href="{% url 'begin:index' %}">Home</a>
            
            <li class="nav-item">
                <a class="one" href="#" id="accountDropdown" style="color: black;">My Account</a>
                <ul class="dropdown-menu" id="dropdownContent">
                    <li><a class="dropdown-item" href="{% url 'main:view-my-books' %}">Books Posted</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:view-wishlist' %}">Wishlist</a></li>
                    <li><a class="dropdown-item" href="{% url 'main:transaction_history' %}">Transaction History</a></li>
                </ul>
            </li>
            
            


</li>
</ul>

</nav>
<br>
{% else %}
<nav class="basenav">

<ul>
	<li>
		<a class="one" href="{% url 'accounts:signup' %}">Register</a>
			<a class="one" href="{% url 'accounts:login' %}">Login</a>
			<a class="one" href= "{% url 'begin:contact' %}"> Contact Us</a>
			<a class="one" href="{% url 'begin:service' %}">Our Services</a>
			<a class="one" href="{% url 'begin:about-us' %}">About Us</a>
			<a class="active one" href=" {% url 'begin:index' %}">Home</a>

</li>
</ul>

</nav>
<br>
{% endif %}
<br>

{% block body %}
None
{% endblock %}

</body>

<!-- Footer Section -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <!-- About Us Section -->
            <div class="col-md-4">
                <h4>About ReBook Connect</h4>
                <p>ReBook Connect is a platform to buy and sell books easily. We connect buyers and sellers, making book exchanges simple and secure.</p>
            </div>

            <!-- Quick Links Section -->
            <div class="col-md-4">
                <h4>Quick Links</h4>
                <ul class="footer-links">
                    <li><a href="{% url 'begin:index' %}">Home</a></li>
                    <li><a href="{% url 'begin:about-us' %}">About Us</a></li>
                    <li><a href="{% url 'begin:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'begin:service' %}">Our Services</a></li>
                </ul>
            </div>

            <!-- Contact Info Section -->
            <div class="col-md-4">
                <h4>Contact Us</h4>
                <p>Email: support@rebookconnect.com</p>
                <p>Phone: +1 (972) 565-0157</p>
                <p>Address: 423 UNT, Texas</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p class="copyright">© 2024 ReBook Connect. All rights reserved.</p>
                
            </div>
        </div>
    </div>
</footer>

<!-- Footer CSS Styling -->
<style>
.footer {
    position: relative; /* Change from fixed to relative */
    background-color: #084787;
    color: white;
    padding: 40px 0;
    margin-top: 50px;
}


.footer .copyright {
    margin-top: 20px;
    font-size: 14px;
    color: #cccccc;
}

.footer h4 {
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 15px;
}

.footer p, .footer-links li a {
    color: #cccccc;
    font-size: 14px;
}

.footer-links {
    list-style: none;
    padding: 0;
}

.footer-links li {
    margin-bottom: 10px;
}

.footer-links li a:hover {
    text-decoration: underline;
    color: white;
}

.copyright {
    margin-top: 20px;
    font-size: 14px;
    color: #cccccc;
}

/* Responsive Footer */
@media (max-width: 768px) {
    .footer .col-md-4 {
        text-align: center;
        margin-bottom: 20px;
    }
    .basenav ul li a {
            font-size: 16px; /* Smaller font size for small screens */
        }
        #mainh1{
            position:absolute;
            top:30%;
            font-size:30px;
            font-weight: normal;
            color: rgb(8, 200, 243);
            text-align:center;
            font-family: 'Aclonica', sans-serif;;

            }
}
</style>
<script>
    // Toggle the visibility of the dropdown
    function toggleDropdown() {
        var dropdown = document.getElementById("dropdownContent");
        if (dropdown.style.display === "none") {
            dropdown.style.display = "block";
        } else {
            dropdown.style.display = "none";
        }
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
        if (!event.target.matches('.one')) {
            var dropdowns = document.getElementsByClassName("dropdown-menu");
            for (var i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.style.display === "block") {
                    openDropdown.style.display = "none";
                }
            }
        }
    }
</script>

</html>

begin/templates/begin/contact.html
{% extends 'begin/base.html' %}
{% load static %}
{% block body %}
<div class="container my-3">
<form action="{% url 'begin:contact' %}" method="post">
    {% csrf_token %}
    <h1>Contact Us</h1>
    <br><br>
    <br>
     <br><br>
    <br> <br><br>
    <br>
    <div class="form-group">
    <label for="name">Name</label>
        <br>
    <input type="name" name="name" class="form-control" id="name" aria-describedby="name" style="margin: 0px;
    width: 637px; ">
    </div>

  <div class="form-group">
    <label for="email">Email address</label>
      <br>
    <input type="email" name="email" class="form-control" id="email" aria-describedby="email" style="margin: 0px;
    width: 637px; ">
  </div>

  <div class="form-group">
    <label for="phone">Phone number</label>
      <br>
    <input type="phone" name="phone" class="form-control" id="phone"  style="margin: 0px;
    width: 637px; ">
  </div>

    <div class="form-group">
    <label for="content">Describe your issues:</label>
        <br>
    <textarea class="form-control" name="content" id="content" cols="30" rows="3" style="margin: 0px;
    width: 637px; height: 237px;"></textarea>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
{% endblock %}

begin/templates/begin/index.html
{% extends 'begin/base.html' %}
{% load static %}
{% block body %}

	<section class="indeximg" >
		<div class="first" >
		<img class="indeximg" width="100%" height="100%"  src="{% static 'images/1.jpeg' %}" >
		<strong><h1 id="mainh1" >Welcome to A Books Reuse and Exchange System</h1></strong>
		<br>
		<br>
		<br>
			<!-- <p id="pmain" >ReBook Connect is a website that links buyers, sellers, and exchangers of secondhand books to make new connections. </p> -->
			</div>
	</section>
{% endblock %}
<!--{% load static %}-->

<!--<html>-->
<!--<head>-->
	<!--<meta charset="utf-8">-->
	<!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
	<!--<link rel="stylesheet" href="{% static 'begin/style.css' %}">-->
	<!--<title>My website</title>-->
	<!--<style>-->
		<!--#mainh1{-->
	<!--position:absolute;-->
	<!--top:50%;-->
	<!--font-size:50px;-->
	<!--color:#800000;-->
	<!--left:20%;-->
<!--}-->
<!--.indeximg{-->
	<!--background-image: "images/books.jpg";-->
	<!--width: 100vw;-->
	<!--height: 100vh;-->
	<!--position: relative;-->
<!--}-->
<!--.one{-->
<!--font-size:30px;-->
<!--text-decoration:none;-->
<!--margin:10px;-->
<!--float:right;-->
<!--top:5px;-->
<!--padding:20px 10px;-->
<!--position:absolute;-->
<!--}-->
<!--.active{-->
<!--left:10%;}-->
<!--.au{-->
<!--left:20%;}-->
<!--.service{-->
<!--left:30%;-->
<!--}-->
<!--.contact{-->
<!--left:45%;}-->
<!--.login{-->
<!--left:60%;}-->
<!--.register{-->
<!--left:70%;}-->
	<!--</style>-->
<!--</head>-->
<!--<body>-->
	<!--<div class="first">-->
	<!--<section class="navbar">-->
		<!--<img class="indeximg" src="{% static 'images/books.jpg' %}" >-->
		<!--<h1 id="mainh1">Recycle Books, Save Money</h1>-->
<!--<nav>-->
	<!--&lt;!&ndash;<h1>&ndash;&gt;-->
		<!--&lt;!&ndash;<ul><li>&ndash;&gt;-->
			<!--&lt;!&ndash;<a class="active one" href="{% url 'begin:index' %}">Home</a>&ndash;&gt;-->
	<!--&lt;!&ndash;<a class="one au" href="{% url 'begin:about-us' %}">About Us</a>&ndash;&gt;-->
	<!--&lt;!&ndash;<a class="one service" href="{% url 'begin:service' %}">Our Services</a>&ndash;&gt;-->
	<!--&lt;!&ndash;<a class="one contact" href="{% url 'begin:contact' %}"> Contact Us</a>&ndash;&gt;-->
	<!--&lt;!&ndash;<a class="one login" href="{% url 'accounts:login' %}">Login</a>&ndash;&gt;-->
	<!--&lt;!&ndash;<a  class="one register" href="{% url 'accounts:signup' %}">Register</a>&ndash;&gt;-->

		<!--&lt;!&ndash;</li></ul>&ndash;&gt;-->
			<!--&lt;!&ndash;</h1>&ndash;&gt;-->


<!--&lt;!&ndash;</nav>&ndash;&gt;-->
		<!--{% include 'begin/base.html' %}-->
<!--</section>-->
<!--</div>-->
<!--</body>-->
<!--</html>-->

begin/templates/begin/service.html
{% extends 'begin/base.html' %}
{% load static %}
{% block body %}
 <!--<section id="services" class="services wow fadeIn">-->
          <!--<div class="container text-center">-->
            <!--<h1 class="title">WHAT WE DO?</h1>-->
             <!--<div class="row text-center">-->

                <!--<div class="col-md-6 services">-->
                    <!--<h4>Detailed Specialist</h4>-->
                    <!--<p>On the basis of disease predicted,we provide you a detailed list of Specialist.</p>-->


                <!--</div>-->
          <!--</section>-->
<section id="services" class="services wow fadeIn">


    <div class="servicediv" style="text-align: center;">
            <p>We offers books to students, readers, and those who require books for short-term use using cheap and cost-effective methods rather than having to purchase new books frequently.  </p>
            <p>Members can easily offer their books in the list they have in stock that are no longer required; this is done by offering book details, prices, and contact information.</p>
        </div>
          </section>
{% endblock %}