ReBook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('begin.urls',namespace='begin')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('main/',include('main.urls',namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import BuyBooks,SellBooks,BuyDetailView,BuyListView,SellCreateView,SellUpdateView,SellDeleteView,searchbooks
from . import views
app_name='main'
urlpatterns=[
    path('buy/',BuyListView.as_view(),name='buy'),
    path('sell/',SellCreateView.as_view(),name='sell'),
    path('detail/<int:pk>/',BuyDetailView.as_view(),name='detail'),
    path('detail/<int:pk>/update/',SellUpdateView.as_view(),name='update'),
    path('detail/<int:pk>/delete/',SellDeleteView.as_view(),name='delete'),
    path('search/',searchbooks,name='search'),
    path('wishlist/add/<int:book_id>/', views.add_to_wishlist, name='add-to-wishlist'),
    path('wishlist/', views.view_wishlist, name='view-wishlist'),
    path('mybooks/', views.view_myBooks, name='view-my-books'),
    path('mark-as-sold/<int:book_id>/', views.mark_as_sold, name='mark_as_sold'),
    path('transaction-history/', views.transaction_history, name='transaction_history'),
    path('add-review/', views.add_review, name='add_review'),


]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Category Table
class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
STATUS_CHOICES = [
        ('available', 'Available'),
        ('sold', 'Sold'),
    ]

# Create your models here.
class Description(models.Model):
    book_name=models.CharField(max_length=100)
    edition=models.CharField(max_length=20)
    location=models.CharField(max_length=20)
    price=models.CharField(max_length=50)
    book_image=models.ImageField(upload_to='book_pic')
    phone=models.CharField(max_length=20,default='')
    seller=models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True, blank=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='available')  # New field for status




    def __str__(self):
        return f"{self.book_name} - {self.category.name if self.category else 'Uncategorized'}"

    def get_absolute_url(self):
        return reverse('main:detail',kwargs={'pk':self.pk})




# Transaction Table
class Transaction(models.Model):
    id = models.AutoField(primary_key=True)
    book = models.ForeignKey(Description, on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return f'Transaction by {self.buyer.username} on {self.date}'



# Wishlist Table
class Wishlist(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Description, on_delete=models.CASCADE)
    

    def __str__(self):
        return f'Wishlist by {self.user.username}'


# Review Table
class Review(models.Model):
    id = models.AutoField(primary_key=True)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()  # Rating could be a number between 1-5 or any scale you decide
    comment = models.TextField()
    transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)

    def __str__(self):
        return f'Review for {self.user.username} - Rating: {self.rating}'

main/forms.py
from django.forms import ModelForm,TextInput
from django import forms
from .models import Description
class SellForm(forms.ModelForm):

    class Meta:
        model=Description
        fields=['book_name','edition','location','price','phone','book_image','seller']
        widgets={
            'book_name':forms.TextInput(attrs={'class': 'form-control'}),
            'edition': TextInput(attrs={'class': 'form-control'}),
            'location': TextInput(attrs={'class': 'form-control'}),
            'price': TextInput(attrs={'class': 'form-control'}),
            'phone': TextInput(attrs={'class': 'form-control'}),
            'seller': TextInput(attrs={'class': 'form-control'}),
            }

main/views.py
from django.shortcuts import render
from .forms import SellForm
from django.contrib.auth.models import User
from .models import Description, Wishlist, Transaction, Review
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin

# Create your views here.
class SellCreateView(LoginRequiredMixin,CreateView):
    model = Description
    fields = ['book_name', 'edition', 'category', 'location', 'price', 'phone', 'book_image']
    template_name = 'main/sell.html'  # Specify the template

    def form_valid(self, form):
        form.instance.seller=self.request.user
        return super().form_valid(form)

class SellUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Description
    fields = ['book_name', 'edition', 'category', 'location', 'price', 'phone', 'book_image']
    template_name = 'main/sell.html'  # Specify the template

    def form_valid(self, form):
        form.instance.seller=self.request.user
        return super().form_valid(form)

    def test_func(self):
        desc=self.get_object()
        if self.request.user==desc.seller:
            return True
        return False



def SellBooks(request):
    u=User.objects.get(id=request.user.id)
    u.save()
    if request.method=='POST':
        form=SellForm(request.POST,request.FILES)
        if form.is_valid():
            print('form is valid')
            form.save()




    elif request.method=='GET':
        form=SellForm()
    context={
        'form':form


    }
    return render(request,'main/sell.html',context)

def BuyBooks(request):
    u=User.objects.all()
    desc=Description.objects.all()
    return render(request,'main/buy.html',{'desc':desc,'u':u})




class BuyListView(ListView):
    model = Description
    template_name = 'main/buy.html'
    context_object_name = 'desc'

    def get_queryset(self):
        # Filter to show only the available books
        return Description.objects.filter(status='available')

from django.db.models import Avg


class BuyDetailView(DetailView):
    model = Description

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Fetch reviews for the specific book
        reviews = Review.objects.filter(transaction__book=self.object)
        context['reviews'] = reviews
        
        # Calculate average rating
        average_rating = reviews.aggregate(Avg('rating'))['rating__avg']
        context['average_rating'] = average_rating if average_rating is not None else 0  # Handle case with no reviews
        
        return context

class SellDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Description
    success_url = '/begin/'


    def test_func(self):
        desc = self.get_object()
        if self.request.user == desc.seller:
            return True
        return False






def DetailofBooks(request,user_id):
    obj=get_object_or_404(User,id=user_id)
    desc = get_object_or_404(Description,id=user_id)
    return render(request,'main/description_detail.html',{'desc':desc,'obj':obj})


def searchbooks(request):
    query=request.GET['query']
    books=Description.objects.filter(book_name__icontains=query)
    return render(request,'main/searchbooks.html',{'desc':books})


from django.contrib import messages
@login_required
def add_to_wishlist(request, book_id):
    book = get_object_or_404(Description, id=book_id)
    
    # Check if the book is already in the user's wishlist
    if Wishlist.objects.filter(user=request.user, book=book).exists():
        messages.info(request, 'This book is already in your wishlist.')
    else:
        # Add the book to the wishlist
        Wishlist.objects.create(user=request.user, book=book)
        messages.success(request, 'Book added to your wishlist!')
    
    return redirect('main:detail', pk=book_id)



@login_required
def view_wishlist(request):
    # Fetch all books in the user's wishlist
    wishlist_books = Wishlist.objects.filter(user=request.user).select_related('book')
    context = {'title':"My Wishlist",
               'books': wishlist_books
               }
    return render(request, 'main/wishlist.html', context)

@login_required
def view_myBooks(request):
    # Fetch all books in the user's wishlist
    books = Description.objects.filter(seller=request.user)
    context = {'title':"Books I have posted",
               'desc': books
               }
    return render(request, 'main/mybooks.html', context)




from django.utils import timezone


@login_required
def mark_as_sold(request, book_id):
    book = get_object_or_404(Description, id=book_id)
    wishlist_users = Wishlist.objects.filter(book=book)

    if request.method == 'POST':
        buyer_id = request.POST.get('buyer_id')
        buyer = get_object_or_404(User, id=buyer_id)

        # Create Transaction
        Transaction.objects.create(book=book, buyer=buyer, date=timezone.now().date())

        # Remove the book from other users' wishlists
        Wishlist.objects.filter(book=book).exclude(user=buyer).delete()

        # Add success message
        messages.success(request, f'Transaction successful! Book sold to {buyer.username}.')

        return redirect('main:detail', pk=book.id)  # Redirect back to book detail page

    return render(request, 'main/mark_as_sold.html', {
        'book': book,
        'wishlist_users': wishlist_users,
    })


@login_required
def transaction_history(request):
    # Transactions where the user is the buyer
    bought_books = Transaction.objects.filter(buyer=request.user)
    
    # Transactions where the user is the seller (i.e., books they've sold)
    sold_books = Transaction.objects.filter(book__seller=request.user)

    return render(request, 'main/transaction_history.html', {
        'bought_books': bought_books,
        'sold_books': sold_books,
    })


@login_required
def add_review(request):
    if request.method == 'POST':
        transaction_id = request.POST.get('transaction_id')
        rating = request.POST.get('rating')
        comment = request.POST.get('comment')

        # Get the transaction for the current user
        transaction = get_object_or_404(Transaction, id=transaction_id, buyer=request.user)

        # Check if a review already exists for this transaction
        review, created = Review.objects.get_or_create(transaction=transaction, user = transaction.book.seller, rating = rating)

        # Only allow updating if the review doesn't exist yet
        if not created:
            messages.error(request, 'You can only leave one review per transaction.')
            return redirect('main:transaction_history')

        # Set the user to be the author of the book being reviewed
        print(transaction.book.seller )
        # review.user = transaction.book.seller  # The seller is the user being reviewed
        # review.rating = rating
        review.comment = comment
        review.save()

        messages.success(request, 'Your review has been submitted successfully.')
        return redirect('main:transaction_history')  # Redirect back to transaction history
    else:
        messages.error(request, 'Invalid request method.')
        return redirect('main:transaction_history')

main/templates/main/buy.html
{% extends 'begin/base.html' %}

{% load static %}
{% block body %}

<div class="container">
  <form method="get" action="{% url 'main:search' %}" class="form-inline ">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
    {% for booksdetail in desc %}
<div class="card-me" style="width: 200px; border:2px solid black;">
  <img src="/media/{{ booksdetail.book_image }}" width="200" height="150" class="card-img-top" alt="...">
  <div class="card-body">
    
    <h5 class="card-title">{{booksdetail.book_name}}</h5>
    <p class="card-text">{{booksdetail.location}}</p>
      <p class="card-text">${{booksdetail.price}}</p>
    <a href="/main/detail/{{booksdetail.id}}" class="btn btn-primary">More Detail</a>
  </div>
</div>



{% endfor %}


    
  </div>

{% endblock %}

main/templates/main/description_confirm_delete.html
{% extends 'begin/base.html' %}
{% block body %}
<div class="container">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

   <fieldset>
       <legend>
           Delete
       </legend>
       <h2>Are you sure to delete {{object.book_name}}</h2>
   </fieldset>
    <button class="btn btn-outline-danger" type="submit">Yes</button>
    <a href="{% url 'main:detail' object.id %}" class="btn btn-outline-secondary" >Cancel</a>
</form>
</div>
{% endblock %}

main/templates/main/description_detail.html
{% extends 'begin/base.html' %}
{% block body %}
<div class="detail" style="margin-left: 5%;">
    
    <h1>Book's Detail</h1>

    <div class="image-side">
        <img src="/media/{{ object.book_image }}" width="400px" height="400px">
    </div>
    <h2>
        Seller: {{ object.seller }} 
        {% if average_rating %}
            <span style="color: orange; font-weight: bold;">(Rated: {{ average_rating|floatformat:1 }} Stars)</span>
        {% endif %}
        <br>
        
        Book's name: {{ object.book_name }}<br>
        Edition: {{ object.edition }}<br>
        Price: {{ object.price }}<br>
        Location: {{ object.location }}<br>
        Contact num: {{ object.phone }}<br>
        {% if object.category %}
            Category: {{ object.category }} <br>
        {% endif %}
    </h2>

    {% if object.seller == user %}
        <a href="{% url 'main:update' object.id %}" class="btn btn-secondary">Update</a>
        <a href="{% url 'main:delete' object.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'main:mark_as_sold' object.id %}" class="btn btn-success">Mark as Sold</a>
    {% endif %}
    
    {% if user.is_authenticated %}
        <a href="{% url 'main:add-to-wishlist' object.id %}" class="btn btn-primary">Add to Wishlist</a>
    {% else %}
        <br><p><a href="{% url 'login' %}">Login</a> to add to wishlist.</p>
    {% endif %}
</div>

<div style="margin-left: 10%;">
    <h3 style="text-align: center;">{{ object.seller }}  Reviews</h3>
    {% if reviews %}
        <ul style="padding: 0;">
            {% for review in reviews %}
            <li style="list-style-type: none; margin-bottom: 15px;">
                <div style="border: 1px solid #ccc; border-radius: 5px; padding: 15px; background-color: #f9f9f9;">
                    <strong>Rating:</strong> <span style="color: orange;">{{ review.rating }} Star</span><br>
                    <strong>Comment:</strong> {{ review.comment }}<br>
                </div>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No reviews yet.</p>
    {% endif %}
</div>

{% endblock %}

main/templates/main/description_form.html
{% extends 'begin/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
<form method="post" enctype="multipart/form-data" class="sell-form">
    {% csrf_token %}

    {{form|crispy}}
    <br>
    <br>
    <button type="submit">Submit</button>
</form>
</div>
{% endblock %}

main/templates/main/mark_as_sold.html
{% extends 'begin/base.html' %}
{% block body %}
<div class="container">
<div class="detail" style="margin-left: 5%;">
    <h1>Mark "{{ book.book_name }}" as Sold</h1>
    <p>Select the user who bought the book:</p>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Username</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for wishlist in wishlist_users %}
                <tr>
                    <td>{{ wishlist.user.username }}</td>
                    <td>
                        <form method="post" style="display:inline;">
                            {% csrf_token %}
                            <input type="hidden" name="buyer_id" value="{{ wishlist.user.id }}">
                            <button
                                type="submit"
                                class="btn btn-success"
                                onclick="return confirmSale()"
                            >
                                Confirm Sale to {{ wishlist.user.username }}
                            </button>
                            <script>
                                function confirmSale() {
                                    return confirm("Are you sure you want to confirm the sale to {{ wishlist.user.username }}?");
                                }
                            </script>

                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="2">No users have added this book to their wishlist.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

</div>
{% endblock %}

main/templates/main/mybooks.html
{% extends 'begin/base.html' %}

{% load static %}
{% block body %}

<div class="container">
    <h1>{{ title }}</h1>
    <br> <br> <br><br> <br> <br>
    {% if desc %}
    {% for booksdetail in desc %}
<div class="card-me" style="width: 200px; border:2px solid black;">
  <img src="/media/{{ booksdetail.book_image }}" width="200" height="150" class="card-img-top" alt="...">
  <div class="card-body">
    
    <h5 class="card-title">{{booksdetail.book_name}}</h5>
    <p class="card-text">{{booksdetail.location}}</p>
      <p class="card-text">${{booksdetail.price}}</p>
    <a href="/main/detail/{{booksdetail.id}}" class="btn btn-primary">More Detail</a>
  </div>
</div>



{% endfor %}

{% else %}
<br> <br> <br> <br> <br>
        <p>You have not posted an Item.</p>
    {% endif %}
</div>

    
  </div>

{% endblock %}

main/templates/main/searchbooks.html
{% extends 'begin/base.html' %}

{% load static %}
{% block body %}


    <style>
  .container {
    display: flex;
    
flex-direction: row;
flex-wrap: wrap;
  }
   .card{
 border:1px solid black;
}
.card-me{
margin:20px;
}

</style>

<br> <br> <br> <br>  <br> <br> <br>
<div class="container">

  {% if desc %}
  <h1>Results Found</h1>
  
    {% for booksdetail in desc %}
<div class="card-me" style="width: 200px; border:2px solid black;">
  <img src="/media/{{booksdetail.book_image}}" width="200px" height="150px" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{booksdetail.book_name}}</h5>
    <p class="card-text">{{booksdetail.location}}</p>
      <p class="card-text">{{booksdetail.price}}</p>
    <a href="/main/detail/{{booksdetail.id}}" class="btn btn-primary">More Detail</a>
  </div>
</div>
{% endfor %}
<!--    <form method="get" action="{% url 'main:search' %}" class="form-inline ">-->
<!--      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->

{% else %}
        <p>No Result Found</p>
    {% endif %}
</div>
  </div>

  {% endblock %}

main/templates/main/sell.html
{% extends 'begin/base.html' %}
{% block body %}
{% load crispy_forms_tags %}
<div class="container">
<div class="">
    <h1>Submit Book Details</h1>
    <br><br>
    <br> <br><br><br> <br><br>
     
    <form method="post" enctype="multipart/form-data">
        
        {% csrf_token %}
    
        {{form|crispy}}
        <button type="submit" class="btn btn-primary" style="background-color: #084787;">Submit</button>
    </form>
   
</div>

</div>
{% endblock %}

main/templates/main/transaction_history.html
{% extends 'begin/base.html' %}
{% block body %}
<style>
    /* Modal styling */
    .modal {
        display: none; /* Hidden by default */
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }
    .modal-content {
        background-color: white;
        margin: 10% auto;
        padding: 20px;
        width: 50%;
        border-radius: 5px;
    }
    .close-btn {
        float: right;
        font-size: 1.5em;
        cursor: pointer;
    }
</style>

<div style="margin-left: 5%;" class="detail">
    <h1>Transaction History</h1>

    <h2>Books I've Bought</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Book Name</th>
                <th>Seller</th>
                <th>Date of Purchase</th>
                <th>Review</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in bought_books %}
                <tr>
                    
                    <td><a href="{% url 'main:detail' transaction.book.id %}">{{ transaction.book.book_name }}</a></td>
                    <td>{{ transaction.book.seller.username }}</td>
                    <td>{{ transaction.date }}</td>
                    <td>
                        {% if transaction.review %}
                            <span>{{transaction.review}} </span>
                        {% else %}
                            <button onclick="openModal({{ transaction.id }})" class="btn btn-primary">Leave Review</button>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">You haven't bought any books yet.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Books I've Sold</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Book Name</th>
                <th>Buyer</th>
                <th>Date of Sale</th>
            </tr>
        </thead>
        <tbody>
            {% for transaction in sold_books %}
                <tr>
                    <td><a href="{% url 'main:detail' transaction.book.id %}">{{ transaction.book.book_name }}</a></td>
                    <td>{{ transaction.buyer.username }}</td>
                    <td>{{ transaction.date }}</td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">You haven't sold any books yet.</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<!-- Review Modal -->
<div id="reviewModal" class="modal">
    <div class="modal-content">
        <span class="close-btn" onclick="closeModal()">&times;</span>
        <h2>Leave a Review</h2>
        <form id="reviewForm" method="post" action="{% url 'main:add_review' %}">
            {% csrf_token %}
            <input type="hidden" name="transaction_id" id="transactionIdField">
            <div class="form-group">
                <label for="rating">Rating:</label>
                <input type="number" name="rating" id="rating" min="1" max="5" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="comment">Comment:</label>
                <textarea name="comment" id="comment" class="form-control" required></textarea>
            </div>
            <button type="submit" class="btn btn-success">Submit Review</button>
        </form>
    </div>
</div>

<script>
    function openModal(transactionId) {
        document.getElementById('reviewModal').style.display = 'block';
        document.getElementById('transactionIdField').value = transactionId;
    }

    function closeModal() {
        document.getElementById('reviewModal').style.display = 'none';
    }

    // Close modal if user clicks outside of it
    window.onclick = function(event) {
        var modal = document.getElementById('reviewModal');
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
{% endblock %}

main/templates/main/wishlist.html
{% extends 'begin/base.html' %}

{% block body %}
<div class="container">
<div class="wishlist-section" style="margin-left: 5%;">
    <h1>{{ title }}</h1>
    <br> <br> <br><br> <br> <br> <br> <br> <br>
    
    {% if books %}
        <ul>
            {% for item in books %} 
                <li>
                    <div class="wishlist-item">
                        <img src="/media/{{ item.book.book_image }}" width="100px" height="100px">
                        <strong>{{ item.book.book_name }}</strong> - {{ item.book.edition }} Edition<br>
                        <span>Price: {{ item.book.price }}</span><br> 
                        <span>Seller: {{ item.book.seller }}</span><br>
                        <a href="{% url 'main:detail' item.book.id %}">View Details</a>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have no items in your wishlist.</p>
    {% endif %}
</div>
</div>
{% endblock %}